[package]
name = "retofa"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.79"
serde_json = "1.0"
thiserror = "1.0"
console_error_panic_hook = "0.1"

[profile.release]
opt-level = "z"
lto = true
